INSERT INTO artist (ARTIST_ID, ARTIST_NAME) VALUES
('A1', 'Drake'),
('A2', 'Deftones'),
('A3', 'Playboi Carti'),
('A4', 'Yeat'),
('A5', 'Lil Uzi Vert'),
('A6', 'Travis Scott'),
('A7', 'Future'),
('A8', 'Joji'),
('A9', 'Korn'),
('A10', 'Artist'),
('A11', 'Artist'),
('A12', 'Artist'),
('A13', 'Artist'),
('A14', 'Artist'),
('A15', 'Artist'),
('A16', 'Artist'),
('A17', 'Artist'),
('A18', 'Artist'),
('A19', 'Artist'),
('A20', 'Artist'),
('A21', 'Artist'),
('A22', 'Artist'),
('A23', 'Artist'),
('A24', 'Artist');
